name: Build and Test
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build-wasm:
        name: Build wasm files for tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: wasm32-wasip1
            - name: Build example wasm
              working-directory: specs/testdata/rust
              run: cargo build
            - name: Upload wasm artifact
              uses: actions/upload-artifact@v4
              with:
                  name: wasm-files
                  path: specs/testdata/rust/target/wasm32-wasip1/debug/example.wasm
    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: build-wasm
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Go toolchain
              uses: actions/setup-go@v5
            - name: Download wasm artifact
              uses: actions/download-artifact@v4
              with:
                  name: wasm-files
                  path: specs/testdata/rust/target/wasm32-wasip1/debug
            - name: Run tests
              run: go test ./specs -wasm testdata/rust/target/wasm32-wasip1/debug/example.wasm
